image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest
initImage:
  repository: bash
  pullPolicy: IfNotPresent
  tag: latest

workload:
  main:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
      initContainers:
        init-cont:
          enabled: true
          type: init
          imageSelector: initImage
          command:
            - /bin/bash
            - -c
            - |
              echo "Hello World"

service:
  main:
    enabled: true
    primary: true
    ports:
      main:
        enabled: true
        primary: true
        port: 8080
        targetPort: 8080
        protocol: http
