imageDictToUse: image
image: &image
  repository: nginx
  tag: 1.19.0
  pullPolicy: IfNotPresent
imageGPU:
  repository: some-gpu-image
  tag: 5.20.0
  pullPolicy: Always
workload:
  workload-name:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      containers:
        container-name1:
          enabled: true
          primary: true
          imageSelector: "{{ .Values.imageDictToUse }}"
          probes: &probes
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
      initContainers:
        container-name2:
          enabled: true
          type: install
          imageSelector: imageGPU
        container-name3:
          enabled: true
          type: install
          imageSelector: imageGPU
        container-name4:
          enabled: true
          type: init
          imageSelector: imageGPU
